### ISSUE TITLE
[CRASH] check_preprocessor_include

### ISSUE THREAD

**Issue by Zekao** [42School/norminette#397] opened 2023-06-29 13:09 UTC
**Describe the bug**
When you forget to put a space between `#include` and `"lib.h"` a crash occurs in the `check_preprocessor_include.py`
**Erroneous code**
```bash
Traceback (most recent call last):
  File "/home/zekao/miniconda3/bin/norminette", line 8, in <module>
    sys.exit(main())
  File "/home/zekao/miniconda3/lib/python3.9/site-packages/norminette/__main__.py", line 128, in main
    registry.run(context, source)
  File "/home/zekao/miniconda3/lib/python3.9/site-packages/norminette/registry.py", line 65, in run
    ret, jump = self.run_rules(context, rule)
  File "/home/zekao/miniconda3/lib/python3.9/site-packages/norminette/registry.py", line 43, in run_rules
    self.run_rules(context, self.rules[r])
  File "/home/zekao/miniconda3/lib/python3.9/site-packages/norminette/registry.py", line 32, in run_rules
    rule.run(context)
  File "/home/zekao/miniconda3/lib/python3.9/site-packages/norminette/rules/check_preprocessor_include.py", line 47, in run
    while tkns[i].type != "NEWLINE" and i < len(tkns) - 1:
IndexError: list index out of range
```

**Additional infos**
 - OS: Ubuntu 22.04.2 LTS
 - python --version: 3.9.12
 - norminette -v: norminette 3.3.52

```c
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   test.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: emaugale <emaugale@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/07/24 21:39:21 by emaugale          #+#    #+#             */
/*   Updated: 2023/06/29 15:02:03 by emaugale         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include"lib.h"

int	main(void)
{
	return (1);
}

```

**Comment by matthieu42Network** [comment] 2023-06-30 08:02
Duplicate of #383

**Closed** 2023-07-12 07:56 UTC
Labels: bug, duplicate
