### ISSUE TITLE
Unable to declare const

### ISSUE THREAD

**Issue by froz0** [42School/norminette#17] opened 2020-12-31 11:41 UTC
` DECL_ASSIGN_LINE     (line: 45, col: 25):       Declaration and assignation on a single line`
`const int               len = ft_len(n);`
**The only way to assign const is to do this :(**

**Comment by Neirpyc** [comment] 2020-12-31 16:32
According to the new _Norm_ (pdf), we are not allowed to use `const` when declaring a function variable anymore. I suppose this is a feature, not a bug.

**Comment by N0ich** [comment] 2021-01-04 14:07
This is a bug, const should be assigned during declaration.
@Neirpyc where did you see that in the norm?

**Comment by Neirpyc** [comment] 2021-01-04 14:16
@N0ich in `https://github.com/42School/norminette/blob/master/pdf/en.norm.tex` from line 146:
```tex
                \item We cannot stick a declaration and an initialisation
                  on the same line, except for global variables (when allowed) and
                  static variables.
```
The new _Norm_ doesn't feature the `const` exception the previous one had and only keeps the `static` and global` ones. Maybe the new _Norm_ is wrong, but I doubt it is.
From the new _Norm_ I deduce that `const` variables are no allowed anymore.

**Comment by N0ich** [comment] 2021-01-04 14:36
You're right, i was mistaken between the const and static keyword.
const is allowed but you cannot initialize it on the same line.

Closing this one, thanks.

**Closed by N0ich** 2021-01-04 14:36 UTC

**Comment by ggjulio** [comment] 2021-01-29 15:00
@N0ich But we cannot assign a constant outside the declaration. Do you mean adding a new line after ` const int n =` ?
Like so ?
```c
int const n =
       13;
```

**Comment by ggjulio** [comment] 2021-02-04 17:04
@N0ich ping

There is still a problem with constant variables in last version (`3.0.2`)

```
test.c: KO!
	DECL_ASSIGN_LINE     (line:  15, col:  31):	Declaration and assignation on a single line
	DECL_ASSIGN_LINE     (line:  25, col:  34):	Declaration and assignation on a single line
	DECL_ASSIGN_LINE     (line:  26, col:  35):	Declaration and assignation on a single line
```

```c
void	test1(void)
{
	const char	*str_test[13] = {"None", "literal", "operator", "op_pipe",
			"op_great", "op_dgreat", "op_less", "quote", "space",
			"variable", "escape", "separator", "end"};
}

void	test2(void)
{
	const char		*conversions = "cspdiuxXnfgeo%";
	const t_handler	jmp_table[14] = {conv_c, conv_s, conv_p, conv_d, conv_i,
		conv_u, conv_x_lowcase,	conv_x_upcase, conv_n, conv_f, conv_g, conv_e,
		conv_o, conv_mod};
}
```

**Comment by abaurens** [comment] 2021-02-26 16:39
> @N0ich in `https://github.com/42School/norminette/blob/master/pdf/en.norm.tex` from line 146:
> 
> ```
>                 \item We cannot stick a declaration and an initialisation
>                   on the same line, except for global variables (when allowed) and
>                   static variables.
> ```
> 
> The new _Norm_ doesn't feature the `const` exception the previous one had and only keeps the `static` and `global` ones. Maybe the new _Norm_ is wrong, but I doubt it is.
> From the new _Norm_ I deduce that `const` variables are no allowed anymore.

And i'd like to point out that the previous norm didn't had any written exception for constants.
It was technically accepted by the norminette V2, but not explicitely written on the PDF.
It's still possible this was removed at least two years ago, but i doubt it somehow..
