### ISSUE TITLE
Line too long, but line only have 74 chars

### ISSUE THREAD

**Issue by andreyvdl** [42School/norminette#447] opened 2023-10-27 00:10 UTC
**Describe the bug**
the norminette detects this line as too long, but the line is just 74 chars.

**Erroneous code**

```c
bool	ft_isspace(int c)
{
	if (c == ' ' & c == '\t' & c == '\n' & c == '\v' & c == '\f' & c == '\r')
		return (true);
	return (false);
}
```

**Additional infos**
 - OS: openSUSE Tumbleweed version 20230915 on Windows 11 x86_64 (Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux)
 - python3 --version: 3.11.5
 - norminette -v: 3.3.54

**Additional context**
```txt
- IsControlStatement In "Function" from "GlobalScope" line 17":
<TAB> <IF> <SPACE> <LPARENTHESIS> <IDENTIFIER=c> <SPACE> <EQUALS> <SPACE> <CHAR_CONST=' '> <SPACE> <BWISE_AND> <SPACE> <IDENTIFIER=c> <SPACE> <EQUALS> <SPACE> <CHAR_CONST='\t'> <SPACE> <BWISE_AND> <SPACE> <IDENTIFIER=c> <SPACE> <EQUALS> <SPACE> <CHAR_CONST='\n'> <SPACE> <BWISE_AND> <SPACE> <IDENTIFIER=c> <SPACE> <EQUALS> <SPACE> <CHAR_CONST='\v'> <SPACE> <BWISE_AND> <SPACE> <IDENTIFIER=c> <SPACE> <EQUALS> <SPACE> <CHAR_CONST='\f'> <SPACE> <BWISE_AND> <SPACE> <IDENTIFIER=c> <SPACE> <EQUALS> <SPACE> <CHAR_CONST='\r'> <RPARENTHESIS> <NEWLINE>
...
Error: LINE_TOO_LONG        (line:  17, col:  82):      line too long
```

I set a red line in the 80 col of my vscode, and as you can see in this print it is inside the limit of the 42 Header, so it has less than 80 col.
![image](https://github.com/42School/norminette/assets/81233149/7e9f0bce-0c19-446a-b550-885b06c7c9bf)

**Comment by matthieu42Network** [comment] 2023-10-30 09:57
duplicate of #439

**Closed** 2023-11-13 08:37 UTC
Labels: bug, duplicate
